name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build Rust WASM
      run: wasm-pack build
